name: terraform

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:
env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v2
      - name: setup terraform
        uses: hashicorp/setup-terraform@v1.2.1
      - name: set stg ENV
        if: github.ref == 'ref/head/develop'
        run: echo "ENV=stg" >> $GITHUB_ENV
      - name: set prod ENV
        if: github.ref == 'ref/head/master'
        run: echo "ENV=stg" >> $GITHUB_ENV
      - name: test
        run: echo $ENV
